# Generated by Django 2.1.7 on 2019-03-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaceRememberApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remember',
            name='user_email',
            field=models.CharField(default=None, max_length=100, verbose_name='Email пользователя'),
        ),
    ]
