# Generated by Django 2.1.7 on 2019-03-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaceRememberApplication', '0004_auto_20190312_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remember',
            name='user_email',
            field=models.CharField(max_length=100, verbose_name='Email пользователя'),
        ),
    ]
