# Generated by Django 2.1.7 on 2019-03-12 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlaceRememberApplication', '0007_auto_20190312_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remember',
            name='user_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
