# Generated by Django 2.1.7 on 2019-03-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlaceRememberApplication', '0008_auto_20190312_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remember',
            old_name='user_email',
            new_name='user',
        ),
    ]
