# Generated by Django 2.1.7 on 2019-03-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaceRememberApplication', '0009_auto_20190312_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remember',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='photos', verbose_name='Фото'),
        ),
    ]
