# Generated by Django 2.1.7 on 2019-03-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaceRememberApplication', '0012_auto_20190314_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remember',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=3, default=-25.344, max_digits=6, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='remember',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=3, default=131.036, max_digits=6, verbose_name='Долгота'),
        ),
    ]
